# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b02d237f38aa03c5c5bae7e951a0a409e8659342a575aab5d2c256ef89e28f364c330eb620702e6c8e432574f0de4c107260ae1431c3d1e4e3556b0d1bb44f

test:
  secret_key_base: f13792a86887398fdd774f7354e807327eaf50acbc743cc381f094189e3ced54780fd1c245429dc59dba96263a5d438aca5173d0b67bc33724a7a85166a17ecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
